### PR TITLE
Add angular2

### PR DESCRIPTION
**Pull request by jarep**
Utworzyłem PR żeby łatwiej widzieć co się dzieje w projekcie. Ja nie mam jeszcze środowiska do angulara.

### CODE REVIEW

**Comment by olaf89** [comment]
Aby odpalic projekt nalezy zainstalowac nodeJS,
nastepnie zainstalowac angular cli (komenda : npm install -g angular-cli)
nastepnie wejsc do forlderu z projektem i odpalic go (ng serve) (trzeba odpalic kolnsole z uprawnieniami administratora)
obecnie zrobiony jest mock symulacji

**Comment by olaf89** [comment]
aa projekt odpali sie na porcie 4200

**Comment by olaf89** [comment]
jak tak jest skonczony to ma zniknac?  czy byc w inProgress / inQueue? czy ma byc jakis box na skonczone taski?
co to jest queue value?
ktos odpalal ta symulacje juz? czego brakuje?

**Comment by jarep** [comment]
Nie mogę odpalić projektu przez ng serve

**W przeglądarce pod http://localhost:4200/ mam coś takiego:**

Build error

The Broccoli Plugin: [Funnel] failed with:

Error: Attempting to watch missing directory: typings
    at EventEmitter.Watcher_addWatchDir [as addWatchDir] (/home/jarep/NetBeansProjects/repos/msom/msom-angular2/node_modules/angular-cli/node_modules/ember-cli/node_modules/broccoli-sane-watcher/index.js:90:11)
    at /home/jarep/NetBeansProjects/repos/msom/msom-angular2/node_modules/angular-cli/node_modules/ember-cli/node_modules/ember-cli-broccoli/lib/builder.js:95:35
    at lib$rsvp$$internal$$tryCatch (/home/jarep/NetBeansProjects/repos/msom/msom-angular2/node_modules/angular-cli/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/home/jarep/NetBeansProjects/repos/msom/msom-angular2/node_modules/angular-cli/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /home/jarep/NetBeansProjects/repos/msom/msom-angular2/node_modules/angular-cli/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/home/jarep/NetBeansProjects/repos/msom/msom-angular2/node_modules/angular-cli/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

The broccoli plugin was instantiated at: 
    at Funnel.Plugin (/home/jarep/NetBeansProjects/repos/msom/msom-angular2/node_modules/angular-cli/node_modules/broccoli-funnel/node_modules/broccoli-plugin/index.js:7:31)
    at new Funnel (/home/jarep/NetBeansProjects/repos/msom/msom-angular2/node_modules/angular-cli/node_modules/broccoli-funnel/index.js:44:10)
    at Angular2App._buildInputTree (/home/jarep/NetBeansProjects/repos/msom/msom-angular2/node_modules/angular-cli/lib/broccoli/angular2-app.js:85:7)
    at new Angular2App (/home/jarep/NetBeansProjects/repos/msom/msom-angular2/node_modules/angular-cli/lib/broccoli/angular2-app.js:51:41)
    at module.exports (/home/jarep/NetBeansProjects/repos/msom/msom-angular2/angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/home/jarep/NetBeansProjects/repos/msom/msom-angular2/node_modules/angular-cli/node_modules/ember-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/home/jarep/NetBeansProjects/repos/msom/msom-angular2/node_modules/angular-cli/node_modules/ember-cli/lib/models/builder.js:89:10)
    at new Class (/home/jarep/NetBeansProjects/repos/msom/msom-angular2/node_modules/angular-cli/node_modules/ember-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/home/jarep/NetBeansProjects/repos/msom/msom-angular2/node_modules/angular-cli/node_modules/ember-cli/lib/tasks/serve.js:15:19)
    at /home/jarep/NetBeansProjects/repos/msom/msom-angular2/node_modules/angular-cli/node_modules/ember-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/home/jarep/NetBeansProjects/repos/msom/msom-angular2/node_modules/angular-cli/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/home/jarep/NetBeansProjects/repos/msom/msom-angular2/node_modules/angular-cli/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /home/jarep/NetBeansProjects/repos/msom/msom-angular2/node_modules/angular-cli/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/home/jarep/NetBeansProjects/repos/msom/msom-angular2/node_modules/angular-cli/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

**W konsoli**
root@debian-jessie:/home/jarep/NetBeansProjects/repos/msom/msom-angular2# ng serve 
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
The Broccoli Plugin: [Funnel] failed with:
Error: Attempting to watch missing directory: typings
    at EventEmitter.Watcher_addWatchDir [as addWatchDir] (/home/jarep/NetBeansProjects/repos/msom/msom-angular2/node_modules/angular-cli/node_modules/angular-cli/node_modules/broccoli-sane-watcher/index.js:90:11)
    at /home/jarep/NetBeansProjects/repos/msom/msom-angular2/node_modules/angular-cli/node_modules/angular-cli/node_modules/angular-cli-broccoli/lib/builder.js:95:35
    at lib$rsvp$$internal$$tryCatch (/home/jarep/NetBeansProjects/repos/msom/msom-angular2/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/home/jarep/NetBeansProjects/repos/msom/msom-angular2/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /home/jarep/NetBeansProjects/repos/msom/msom-angular2/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/home/jarep/NetBeansProjects/repos/msom/msom-angular2/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

The broccoli plugin was instantiated at: 
    at Funnel.Plugin (/home/jarep/NetBeansProjects/repos/msom/msom-angular2/node_modules/angular-cli/node_modules/broccoli-funnel/node_modules/broccoli-plugin/index.js:7:31)
    at new Funnel (/home/jarep/NetBeansProjects/repos/msom/msom-angular2/node_modules/angular-cli/node_modules/broccoli-funnel/index.js:44:10)
    at Angular2App._buildInputTree (/home/jarep/NetBeansProjects/repos/msom/msom-angular2/node_modules/angular-cli/lib/broccoli/angular2-app.js:85:7)
    at new Angular2App (/home/jarep/NetBeansProjects/repos/msom/msom-angular2/node_modules/angular-cli/lib/broccoli/angular2-app.js:51:41)
    at module.exports (/home/jarep/NetBeansProjects/repos/msom/msom-angular2/angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/home/jarep/NetBeansProjects/repos/msom/msom-angular2/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/home/jarep/NetBeansProjects/repos/msom/msom-angular2/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/home/jarep/NetBeansProjects/repos/msom/msom-angular2/node_modules/angular-cli/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/home/jarep/NetBeansProjects/repos/msom/msom-angular2/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/serve.js:15:19)
    at /home/jarep/NetBeansProjects/repos/msom/msom-angular2/node_modules/angular-cli/node_modules/angular-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/home/jarep/NetBeansProjects/repos/msom/msom-angular2/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/home/jarep/NetBeansProjects/repos/msom/msom-angular2/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /home/jarep/NetBeansProjects/repos/msom/msom-angular2/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/home/jarep/NetBeansProjects/repos/msom/msom-angular2/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

**Comment by jarep** [comment]
próbowałem jako root, doinstalowałem też:
npm i -g typings
i już nie pamiętam co jeszcze.

**Comment by jarep** [comment]
Task jak zostanie zakończony przez jeden moduł(kontroler) to może zostać przekazany do kolejnego. Gdy isFinished to znika z list wykonywanych zadań. Można ew. osobno wyświetlać listę zakończonych tasków żeby dostarczyć danych na ich temat, ale w tym momencie chyba interfejsy nie przewidują zwracania listy zakończonych tasków (o ile dobrze pamiętam).

**Comment by jarep** [comment]
QueueValue to suma wszystkich taskDifficulty będących w kolejce.

**Comment by olaf89** [comment]
@jarep mogl mbys sprobowac komende "typings install"?

**Comment by olaf89** [comment]
zrobiłem merge api-json-controller brancha, i zmienilem metody które będą potrzebne client juz jest w stanie pobierac dane, 
startSimulation nie musi niczego zwracac, natomiast w momencie gdy zostanie zawolane z ID symulacji symulacja powinna sie rozpoczac na serwerze i zaczna sie requesty po dane.

Zauważyłem że modele które używamy nie są takie same @jarep jak możesz to sprawdz czy SimulationReport model jest ostatecznym ktory bedzie użyty.

**Comment by jarep** [comment]
Olaf, mówiłeś że nie bedziemy korzystac z klasy SimulationReport. Klasy modelu są w pakiecie model, a właściwie to ich nie ma bo nie zostały zrobione implementacje interfejsów.

**Comment by olaf89** [comment]
model może się nazywać dowolnie, jednak dane zwracane przez api musza mięć jakaś strukturę. Chodziło mi o to że nie musi byc udostępnionych 5 endopointów każdy zwracający osobny report, tylko wystarczy jeden który zwróci wszystkie informację. Niezależnie od tego które podejście zostanie wybrane potrzebuje dostać deklarację modelu struktury danych która zostanie zwrócona, żeby móc się przygotować do jej przetworzenia.

**Pull request closed without merging**
